### ISSUE TITLE
当购物车数据条数有19条以上时，删除购物车数据会闪退

### ISSUE THREAD

**Issue by ziyouxiaozi** [DingXianSen/ProDemo#2]
当购物车数据条数有19条以上时，有时删除购物车数据会闪退！

**Comment by DingXianSen** [comment]
看看数据parentId和productId是不是有一致的数据，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liwq"<notifications@github.com&gt;; 
发送时间: 2020年12月15日(星期二) 上午10:16
收件人: "DingXianSen/ProDemo"<ProDemo@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [DingXianSen/ProDemo] 当购物车数据条数有19条以上时，删除购物车数据会闪退 (#2)





 
当购物车数据条数有19条以上时，删除购物车数据会闪退，而且当前点击删除的项并没有被删除，而是删除其他项！

**Comment by ziyouxiaozi** [comment]
在ProDemo里的分组列表的更换空气滤芯4和更换空调滤芯4好像是重复了parentId和productId，当我点击删除这两个item的数据时，这两个item的数量并没有变少，而是其他的item被删了，当删除到只有最后一条数据时就闪退了！

**Comment by DingXianSen** [comment]
错误日志，截图看下，另外看下你的删除操作是怎样的，是数量删除还是单条目删除



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liwq"<notifications@github.com&gt;; 
发送时间: 2020年12月15日(星期二) 上午10:43
收件人: "DingXianSen/ProDemo"<ProDemo@noreply.github.com&gt;; 
抄送: "丁先森"<dingchao7323@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [DingXianSen/ProDemo] 当购物车数据条数有19条以上时，删除购物车数据会闪退 (#2)





 
在ProDemo里的分组列表的更换空气滤芯4和更换空调滤芯4好像是重复了parentId和productId，当我点击删除这两个item的数据时，这两个item的数量并没有变少，而是其他的item被删了，当删除到只有最后一条数据时就闪退了！

**Comment by ziyouxiaozi** [comment]
不懂为什么我这边没有打印错误日志，当从第一条数据开始往购物车里添加数据一直添加到更换空调滤芯这个为止，其中动力提升1这个项里的item数据数量都添加3个以上，然后点击购物车弹窗出来后拉到底部，点击删除倒数第二个item的数量，我这边的item商品名是更换空调滤芯4。当你点击减号删的时候，删除的是当前点击项的下一条，而不是它本身的数量变少！

**Comment by ziyouxiaozi** [comment]
![Uploading image.png…]()

**Comment by DingXianSen** [comment]
可以加我QQ：1461117323，QQ沟通会方便一些



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liwq"<notifications@github.com&gt;; 
发送时间: 2020年12月15日(星期二) 上午10:54
收件人: "DingXianSen/ProDemo"<ProDemo@noreply.github.com&gt;; 
抄送: "丁先森"<dingchao7323@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [DingXianSen/ProDemo] 当购物车数据条数有19条以上时，删除购物车数据会闪退 (#2)





 
不懂为什么我这边没有打印错误日志，当从第一条数据开始往购物车里添加数据一直添加到更换空调滤芯这个为止，其中动力提升1这个项里的item数据数量都添加3个以上，然后点击购物车弹窗出来后拉到底部，点击删除倒数第二个item的数量，我这边的item商品名是更换空调滤芯4。当你点击减号删的时候，删除的是当前点击项的下一条，而不是它本身的数量变少！
